### ISSUE TITLE
Crash in MPD browse of "Explore/Drum & Bass" because of Ref.name which is None

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-soundcloud#31]
``` python
INFO     Loaded 57 Spotify playlists
INFO     Song 161665785 was removed
ERROR    Unhandled exception in MpdSession (urn:uuid:39ca2a02-eab4-4c0a-9f6c-b83f20256c77):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/home/jodal/dev/mopidy/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/home/jodal/dev/mopidy/mopidy/mpd/session.py", line 33, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 46, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 75, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 85, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 104, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 133, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 146, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 158, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 167, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/home/jodal/dev/mopidy/mopidy/mpd/protocol/__init__.py", line 178, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/home/jodal/dev/mopidy/mopidy/mpd/protocol/__init__.py", line 156, in validate
    return func(**callargs)
  File "/home/jodal/dev/mopidy/mopidy/mpd/protocol/music_db.py", line 413, in lsinfo
    for path, lookup_future in context.browse(uri, recursive=False):
  File "/home/jodal/dev/mopidy/mopidy/mpd/dispatcher.py", line 320, in browse
    path = '/'.join([base_path, ref.name.replace('/', '')])
AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/jodal/dev/mopidy/mopidy/utils/network.py", line 271, in recv_callback
    self.actor_ref.tell({'close': True})
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)
pykka.exceptions.ActorDeadError: MpdSession (urn:uuid:39ca2a02-eab4-4c0a-9f6c-b83f20256c77) not found
INFO     New MPD connection from [::ffff:127.0.0.1]:35489
```

**Comment by jodal** [comment]
> *This was generated by AI during triage.*

The Explore folder was removed from Mopidy-SoundCloud, and the code in this traceback no longer exists. Closing. Please open a new issue if browsing crashes with the current version.
