### ISSUE TITLE
Soundcloud backend exception when using explore

### ISSUE THREAD

**Issue by Chudders** [mopidy/mopidy-soundcloud#82]
Hi there. Me again. Sorry for being a nuisance, Soundcloud mostly works, but I cannot explore, which is sad as it's one of it's best features. I get the following error:

> ERROR    SoundCloudBackend backend caused an exception.
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
>     yield
>   File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
>     result = backend.library.browse(uri).get()
>   File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
>     compat.reraise(_self._data['exc_info'])
>   File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
>     exec('raise tp, value, tb')
>   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
>     response = self._handle_receive(message)
>   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
>     return callee(_message['args'], *_message['kwargs'])
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/library.py", line 155, in browse
>     return self.list_explore()
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/library.py", line 97, in list_explore
>     for eid, name in enumerate(self.backend.remote.get_explore()):
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 116, in get_explore
>     explore = self.get_explore_categories()
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 57, in _memoized
>     value = self.func(_args)
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 113, in get_explore_categories
>     return self._get('explore/categories', 'api-v2').get('music')
>   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 235, in _get
>     res.raise_for_status()
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 825, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> HTTPError: 404 Client Error: Not Found

I can get all my liked tracks, sets, stream but not explore (or 'following' or 'groups' for that matter, althought I consider them much less important). 

Appreciate some pointers if at all possible.

**Comment by blueyed** [comment]
According to https://github.com/mopidy/mopidy-soundcloud/pull/83 the API has been removed for this?
But maybe it only moved?

**Comment by emprovements** [comment]
Getting similar error:
ERROR    SoundCloudBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/library.py", line 155, in browse
    return self.list_explore()
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/library.py", line 97, in list_explore
    for eid, name in enumerate(self.backend.remote.get_explore()):
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 116, in get_explore
    explore = self.get_explore_categories()
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 57, in _memoized
    value = self.func(*args)
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 113, in get_explore_categories
    return self._get('explore/categories', 'api-v2').get('music')
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/soundcloud.py", line 235, in _get
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://api-v2.soundcloud.com/explore/categories?client_id=93e13e327fd8a9d77becd179652272j2

**Comment by kingosticks** [comment]
#100 included numerous PRs updating abd fixing the use of these deprecated v2 APIs. This should be fixed in the next release.
